Document: tla-load-dirs
Title: Debian tla-load-dirs Manual
Author: <insert document author here>
Abstract: This manual describes what tla-load-dirs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tla-load-dirs/tla-load-dirs.sgml.gz

Format: postscript
Files: /usr/share/doc/tla-load-dirs/tla-load-dirs.ps.gz

Format: text
Files: /usr/share/doc/tla-load-dirs/tla-load-dirs.text.gz

Format: HTML
Index: /usr/share/doc/tla-load-dirs/html/index.html
Files: /usr/share/doc/tla-load-dirs/html/*.html

  
